import './globals.css';
import { DM_Sans } from 'next/font/google';
import Header from '../components/Header';
import Footer from '../components/Footer';

import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import ScrollToTopButton from '@/components/ui/scrollToTopButton';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased grid bg-[#070815] text-white',
          fontSans.variable,
        )}
      >
        <Header />
        <main>{children}</main>
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
